import type { Metadata } from "next";
import { Poppins, Anonymous_Pro } from "next/font/google";

import "./globals.css";
import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/Navbar";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-poppins",
});

const anon_pro = Anonymous_Pro({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-anon-pro",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${anon_pro.variable} min-h-screen flex flex-col`}
      >
        <Navbar />
        <main className="flex h-[calc(100vh-72px)] flex-col items-center justify-center lg:px-20 lg:pt-10 lg:pb-20 bg-primary-gradient">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
